///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KALPI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KALPIRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("09cceba5-9f82-44be-aa65-925499136ce1")]
    public partial class KALPIRepository : RepoGenBaseFolder
    {
        static KALPIRepository instance = new KALPIRepository();
        KALPIRepositoryFolders.StartAppFolder _start;
        KALPIRepositoryFolders.KALPILoginMozillaFirefoxPrivateAppFolder _kalpiloginmozillafirefoxprivate;

        /// <summary>
        /// Gets the singleton class instance representing the KALPIRepository element repository.
        /// </summary>
        [RepositoryFolder("09cceba5-9f82-44be-aa65-925499136ce1")]
        public static KALPIRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KALPIRepository() 
            : base("KALPIRepository", "/", null, 0, false, "09cceba5-9f82-44be-aa65-925499136ce1", ".\\RepositoryImages\\KALPIRepository09cceba5.rximgres")
        {
            _start = new KALPIRepositoryFolders.StartAppFolder(this);
            _kalpiloginmozillafirefoxprivate = new KALPIRepositoryFolders.KALPILoginMozillaFirefoxPrivateAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09cceba5-9f82-44be-aa65-925499136ce1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Start folder.
        /// </summary>
        [RepositoryFolder("45208ce9-229f-4fb4-8978-48a5f38dca3c")]
        public virtual KALPIRepositoryFolders.StartAppFolder Start
        {
            get { return _start; }
        }

        /// <summary>
        /// The KALPILoginMozillaFirefoxPrivate folder.
        /// </summary>
        [RepositoryFolder("58359e94-b739-4147-89b3-b8b71e5dda86")]
        public virtual KALPIRepositoryFolders.KALPILoginMozillaFirefoxPrivateAppFolder KALPILoginMozillaFirefoxPrivate
        {
            get { return _kalpiloginmozillafirefoxprivate; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class KALPIRepositoryFolders
    {
        /// <summary>
        /// The StartAppFolder folder.
        /// </summary>
        [RepositoryFolder("45208ce9-229f-4fb4-8978-48a5f38dca3c")]
        public partial class StartAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tilemicrosoftbingfinance8wekyb3d8bbweInfo;
            RepoItemInfo _container9a072f49836b4bafad70e3dc6cInfo;
            RepoItemInfo _tilemicrosoftxboxapp8wekyb3d8bbwemicrInfo;

            /// <summary>
            /// Creates a new Start  folder.
            /// </summary>
            public StartAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Start", "/winapp[@appid='App' and @name='Start']", parentFolder, 30000, null, true, "45208ce9-229f-4fb4-8978-48a5f38dca3c", "")
            {
                _tilemicrosoftbingfinance8wekyb3d8bbweInfo = new RepoItemInfo(this, "TileMicrosoftBingFinance8wekyb3d8bbwe", ".//container[@automationid='{9a072f49-836b-4baf-ad70-e3dc6cdb068f}']/listitem[@automationid='tile-Microsoft.BingFinance_8wekyb3d8bbwe!AppexFinance']", 30000, null, "ac030688-56ea-4bb7-b3c7-90a98bdfaa25");
                _container9a072f49836b4bafad70e3dc6cInfo = new RepoItemInfo(this, "Container9a072f49836b4bafAd70E3dc6c", "?/?/list[@automationid='groupItems']/container[@automationid='{9a072f49-836b-4baf-ad70-e3dc6cdb068f}']", 30000, null, "74c76b2b-923f-4105-92bb-d589e4128f58");
                _tilemicrosoftxboxapp8wekyb3d8bbwemicrInfo = new RepoItemInfo(this, "TileMicrosoftXboxApp8wekyb3d8bbweMicr", ".//container[@automationid='{9a072f49-836b-4baf-ad70-e3dc6cdb068f}']/listitem[@automationid='tile-Microsoft.XboxApp_8wekyb3d8bbwe!Microsoft.XboxApp']", 30000, null, "3bc72b96-cd37-4957-aa8f-cb075c420096");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45208ce9-229f-4fb4-8978-48a5f38dca3c")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45208ce9-229f-4fb4-8978-48a5f38dca3c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TileMicrosoftBingFinance8wekyb3d8bbwe item.
            /// </summary>
            [RepositoryItem("ac030688-56ea-4bb7-b3c7-90a98bdfaa25")]
            public virtual Ranorex.ListItem TileMicrosoftBingFinance8wekyb3d8bbwe
            {
                get
                {
                    return _tilemicrosoftbingfinance8wekyb3d8bbweInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TileMicrosoftBingFinance8wekyb3d8bbwe item info.
            /// </summary>
            [RepositoryItemInfo("ac030688-56ea-4bb7-b3c7-90a98bdfaa25")]
            public virtual RepoItemInfo TileMicrosoftBingFinance8wekyb3d8bbweInfo
            {
                get
                {
                    return _tilemicrosoftbingfinance8wekyb3d8bbweInfo;
                }
            }

            /// <summary>
            /// The Container9a072f49836b4bafAd70E3dc6c item.
            /// </summary>
            [RepositoryItem("74c76b2b-923f-4105-92bb-d589e4128f58")]
            public virtual Ranorex.Container Container9a072f49836b4bafAd70E3dc6c
            {
                get
                {
                    return _container9a072f49836b4bafad70e3dc6cInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Container9a072f49836b4bafAd70E3dc6c item info.
            /// </summary>
            [RepositoryItemInfo("74c76b2b-923f-4105-92bb-d589e4128f58")]
            public virtual RepoItemInfo Container9a072f49836b4bafAd70E3dc6cInfo
            {
                get
                {
                    return _container9a072f49836b4bafad70e3dc6cInfo;
                }
            }

            /// <summary>
            /// The TileMicrosoftXboxApp8wekyb3d8bbweMicr item.
            /// </summary>
            [RepositoryItem("3bc72b96-cd37-4957-aa8f-cb075c420096")]
            public virtual Ranorex.ListItem TileMicrosoftXboxApp8wekyb3d8bbweMicr
            {
                get
                {
                    return _tilemicrosoftxboxapp8wekyb3d8bbwemicrInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TileMicrosoftXboxApp8wekyb3d8bbweMicr item info.
            /// </summary>
            [RepositoryItemInfo("3bc72b96-cd37-4957-aa8f-cb075c420096")]
            public virtual RepoItemInfo TileMicrosoftXboxApp8wekyb3d8bbweMicrInfo
            {
                get
                {
                    return _tilemicrosoftxboxapp8wekyb3d8bbwemicrInfo;
                }
            }
        }

        /// <summary>
        /// The KALPILoginMozillaFirefoxPrivateAppFolder folder.
        /// </summary>
        [RepositoryFolder("58359e94-b739-4147-89b3-b8b71e5dda86")]
        public partial class KALPILoginMozillaFirefoxPrivateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new KALPILoginMozillaFirefoxPrivate  folder.
            /// </summary>
            public KALPILoginMozillaFirefoxPrivateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KALPILoginMozillaFirefoxPrivate", "/form[@title~'^KALPI\\ \\|\\ Login\\ -\\ Mozilla\\ F']", parentFolder, 30000, null, true, "58359e94-b739-4147-89b3-b8b71e5dda86", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@accessiblerole='Grouping']/container[7]/?/?/container[@accessiblename='KALPI | Login']/element/element[@accessiblerole='None']/element[2]/element/element[2]/?/?/text[@accessiblename='Password']", 30000, null, "b9d64702-5ece-417a-afe1-f48361783b60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58359e94-b739-4147-89b3-b8b71e5dda86")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58359e94-b739-4147-89b3-b8b71e5dda86")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("b9d64702-5ece-417a-afe1-f48361783b60")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("b9d64702-5ece-417a-afe1-f48361783b60")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}